from flask import Flask, render_template, request, jsonify, send_file
import os
import json
import tempfile
from werkzeug.utils import secure_filename
from datetime import datetime
import traceback

# Import our existing workflow functions
from pa_form_automation_workflow import (
    extract_text_from_pdf,
    extract_info_with_openai,
    map_to_pa_form_fields
)

app = Flask(__name__)
app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024  # 16MB max file size
app.config['UPLOAD_FOLDER'] = 'uploads'
app.config['SECRET_KEY'] = 'your-secret-key-here'

# Ensure upload directory exists
os.makedirs(app.config['UPLOAD_FOLDER'], exist_ok=True)
os.makedirs('output/filled_forms', exist_ok=True)
os.makedirs('output/reports', exist_ok=True)

ALLOWED_EXTENSIONS = {'pdf'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/upload', methods=['POST'])
def upload_file():
    try:
        if 'file' not in request.files:
            return jsonify({'error': 'No file provided'}), 400
        
        file = request.files['file']
        if file.filename == '':
            return jsonify({'error': 'No file selected'}), 400
        
        if not allowed_file(file.filename):
            return jsonify({'error': 'Only PDF files are allowed'}), 400
        
        # Save uploaded file
        filename = secure_filename(file.filename)
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"{timestamp}_{filename}"
        filepath = os.path.join(app.config['UPLOAD_FOLDER'], filename)
        file.save(filepath)
        
        # Process the file
        result = process_pdf_file(filepath)
        
        # Clean up uploaded file
        os.remove(filepath)
        
        return jsonify(result)
    
    except Exception as e:
        return jsonify({
            'error': 'Processing failed',
            'details': str(e),
            'traceback': traceback.format_exc()
        }), 500

def process_pdf_file(filepath):
    """Process a PDF file through the automation workflow"""
    try:
        # Step 1: Extract text from PDF
        print(f"Processing: {filepath}")
        extracted_text = extract_text_from_pdf(filepath)
        
        if not extracted_text.strip():
            return {
                'error': 'No text could be extracted from the PDF. The file might be corrupted or contain only images.',
                'extracted_text': ''
            }
        
        # Step 2: Extract structured info with OpenAI
        print("Extracting structured info with OpenAI...")
        info_json = extract_info_with_openai(extracted_text)
        
        # Step 3: Map to PA form fields
        pa_fields = map_to_pa_form_fields(info_json)
        
        # Step 4: Generate report
        report = generate_processing_report(filepath, extracted_text, info_json, pa_fields)
        
        return {
            'success': True,
            'filename': os.path.basename(filepath),
            'extracted_text': extracted_text[:1000] + '...' if len(extracted_text) > 1000 else extracted_text,
            'structured_info': info_json,
            'pa_form_fields': pa_fields,
            'report': report
        }
    
    except Exception as e:
        raise Exception(f"Error processing PDF: {str(e)}")

def generate_processing_report(filepath, extracted_text, info_json, pa_fields):
    """Generate a processing report"""
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    report = f"""
# PA Form Automation Processing Report

**File Processed:** {os.path.basename(filepath)}
**Processing Time:** {timestamp}

## Extracted Information

### Structured Data
```json
{json.dumps(json.loads(info_json) if isinstance(info_json, str) else info_json, indent=2)}
```

### PA Form Fields
"""
    
    for field, value in pa_fields.items():
        report += f"- **{field}:** {value}\n"
    
    report += f"""
## Raw Extracted Text
```
{extracted_text[:500]}...
```

---
*Report generated by PA Form Automation System*
"""
    
    # Save report to file
    report_filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    report_path = os.path.join('output/reports', report_filename)
    
    with open(report_path, 'w') as f:
        f.write(report)
    
    return report

@app.route('/health')
def health_check():
    return jsonify({'status': 'healthy', 'timestamp': datetime.now().isoformat()})

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5001) 